# Generated by Django 3.2.16 on 2024-03-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token_value',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
