# Generated by Django 3.2.16 on 2024-03-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0002_alter_token_token_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='date',
            new_name='date_responce',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='token_value',
            new_name='chat_token',
        ),
        migrations.RemoveField(
            model_name='token',
            name='status',
        ),
        migrations.AddField(
            model_name='message',
            name='date_request',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
